2024-10-16 08:25:11,631 - qm - INFO     - Starting session: 7316adab-f0d9-4fd7-86a0-1e007b85b87f
2024-10-16 08:25:14,394 - qm - INFO     - Octave "octave2" Health check passed, current temperature 60
2024-10-16 08:25:15,125 - qm - INFO     - Octave "octave3" Health check passed, current temperature 57
2024-10-16 08:25:15,860 - qm - INFO     - Octave "octave4" Health check passed, current temperature 58
2024-10-16 08:25:16,893 - qm - INFO     - Octave "octave5" Health check passed, current temperature 59
2024-10-16 08:25:17,906 - qm - INFO     - Octave "octave6" Health check passed, current temperature 58
2024-10-16 08:25:17,906 - qm - INFO     - Performing health check
2024-10-16 08:25:17,926 - qm - WARNING  - Health check warning: Inter-OPX connectivity issues in OPX: con1. Missing ports are: 12, 11, 10, 9. See QM-App for more info.
2024-10-16 08:25:17,926 - qm - WARNING  - Health check warning: Inter-OPX connectivity issues in OPX: con2. Missing ports are: 12, 11, 10, 9. See QM-App for more info.
2024-10-16 08:25:17,926 - qm - WARNING  - Health check warning: Inter-OPX connectivity issues in OPX: con3. Missing ports are: 12, 11, 10, 9. See QM-App for more info.
2024-10-16 08:25:17,926 - qm - WARNING  - Health check warning: Inter-OPX connectivity issues in OPX: con4. Missing ports are: 12, 11, 10, 9. See QM-App for more info.
2024-10-16 08:25:17,926 - qm - WARNING  - Health check warning: Inter-OPX connectivity issues in OPX: con5. Missing ports are: 12, 11, 10, 9. See QM-App for more info.
2024-10-16 08:25:17,926 - qm - WARNING  - Health check warning: Inter-OPX connectivity issues in OPX: con6. Missing ports are: 12, 11, 10, 9. See QM-App for more info.
2024-10-16 08:25:17,926 - qm - WARNING  - Health check warning: Inter-OPX connectivity issues in OPX: con7. Missing ports are: 12, 11, 10, 9. See QM-App for more info.
2024-10-16 08:25:17,926 - qm - WARNING  - Health check warning: Inter-OPX connectivity issues in OPX: con8. Missing ports are: 12, 11, 10, 9. See QM-App for more info.
2024-10-16 08:25:17,926 - qm - WARNING  - Health check warning: Inter-OPX connectivity issues in OPX: con9. Missing ports are: 12, 11, 10, 9. See QM-App for more info.
2024-10-16 08:25:17,926 - qm - INFO     - Health check passed
Connected to: Rohde&Schwarz SGS100A (serial:1416.0505k02/114167, firmware:4.2.76.0-4.30.046.295) in 0.18s
Connected to: Rohde&Schwarz SGS100A (serial:1416.0505k02/114164, firmware:4.2.76.0-4.30.046.295) in 0.14s
2024-10-16 08:25:21,033 - qm - INFO     - Sending program to QOP for compilation
2024-10-16 08:25:21,200 - qm - INFO     - Executing program
2024-10-16 08:25:24,516 - qm - ERROR    - CONFIG ERROR in key "mixers.driveD1_mixer_a8f" [mixers.corrections.intermediateFrequency.values] : Mixer 'driveD1_mixer_a8f' correction 'FrequencyCorrection(frequency=8.26543305E8, loFrequency=5.1E9, correction=CorrectionMatrix(v00=1.0, v01=0.0, v10=0.0, v11=1.0))' has an intermediate frequency greater than 5.0E8
2024-10-16 08:25:24,516 - qm - ERROR    - CONFIG ERROR in key "elements.driveD1" [element.intermediateFrequencyUpperLimit] : Element 'driveD1' has intermediate frequency greater than 5.0E8 (8.26543305E8)
Traceback (most recent call last):
  File "/nfs/users/elisa.stabilini/calibration/bin/qq", line 8, in <module>
    sys.exit(command())
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/users/elisa.stabilini/qibocal/src/qibocal/cli/_base.py", line 75, in auto
    autocalibrate(runcard, folder, force, update)
  File "/nfs/users/elisa.stabilini/qibocal/src/qibocal/cli/autocalibration.py", line 42, in autocalibrate
    history = runcard.run(
  File "/nfs/users/elisa.stabilini/qibocal/src/qibocal/auto/runcard.py", line 63, in run
    instance.run_protocol(
  File "/nfs/users/elisa.stabilini/qibocal/src/qibocal/auto/execute.py", line 131, in run_protocol
    completed = task.run(platform=self.platform, targets=self.targets, mode=mode)
  File "/nfs/users/elisa.stabilini/qibocal/src/qibocal/auto/task.py", line 149, in run
    completed.data, completed.data_time = operation.acquisition(
  File "/nfs/users/elisa.stabilini/qibocal/src/qibocal/auto/operation.py", line 42, in wrapper
    out = func(*args, **kwds)
  File "/nfs/users/elisa.stabilini/qibocal/src/qibocal/protocols/classification.py", line 217, in _acquisition
    results = [
  File "/nfs/users/elisa.stabilini/qibocal/src/qibocal/protocols/classification.py", line 218, in <listcomp>
    platform.execute_pulse_sequence(sequence, options) for sequence in sequences
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/qibolab/platform/platform.py", line 196, in execute_pulse_sequence
    return self._execute(sequence, options, **kwargs)
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/qibolab/platform/platform.py", line 170, in _execute
    new_result = instrument.play(
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/qibolab/instruments/qm/controller.py", line 355, in play
    return self.sweep(qubits, couplers, sequence, options)
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/qibolab/instruments/qm/controller.py", line 402, in sweep
    result = self.execute_program(experiment)
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/qibolab/instruments/qm/controller.py", line 288, in execute_program
    machine = self.manager.open_qm(self.config.__dict__)
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/qm/quantum_machines_manager.py", line 249, in open_qm
    machine_id = self._frontend.open_qm(loaded_config, close_other_machines)
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/qm/api/base_api.py", line 28, in wrapped
    return func(*args, **kwargs)
  File "/nfs/users/elisa.stabilini/calibration/lib/python3.10/site-packages/qm/api/frontend_api.py", line 129, in open_qm
    raise OpenQmException("Can not open QM. Please see previous errors", errors=errors)
qm.exceptions.OpenQmException: Can not open QM. Please see previous errors
